version: '3'

services:
# The NGINX web/reverse-proxy server.
  nginx-proxy:
    restart: always
    depends_on:
      - app
    networks:
      - laratt-network
    image: nginx:latest
    ports:
      - 9088:80
    volumes:
      - "./.docker/conf/site.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/public:ro"
      # Remove the comment below to enable nginx logs.
      #- "./logs/:/var/log/nginx/"

# The Laravel app.
  app:
    restart: always
    depends_on:
      - dbhost
    networks:
      - laratt-network
    image: cyberduck/php-fpm-laravel:7.2
    volumes:
      - "./:/var/www"

# The database server.
  dbhost:
    restart: always
    image: mariadb:10.2
    networks:
      - laratt-network
    hostname: dbhost
    command: ["mysqld", "--innodb-buffer-pool-size=1G"]
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=laratt"
      - "MYSQL_PASSWORD=secret"
    volumes:
      - "./.docker/conf/my.cnf:/etc/mysql/my.cnf:ro"
      - "./.docker/data/mysql:/var/lib/mysql:rw"

# The redis caching server.
# redis:
#   image: redis:4-alpine
#   restart: always
#   hostname: redis
#   command: ["redis-server", "--appendonly", "yes"]
#   networks:
#     - laratt-network
#   volumes:
#     - redis-data:/data

# (Optional) A PHPMyAdmin web interface for the database.
#    phpmyadmin:
#      depends_on:
#        - db
#      image: phpmyadmin/phpmyadmin
#      restart: always
#      ports:
#        - 8080:80
#      env_file:
#        - ./config/mysql.env
#      environment:
#        PMA_HOST: db
#      networks:
#        - app-network

networks:
  laratt-network:

volumes:
  redis-data:
